version: "3.3"

services:
  db:
    platform: linux/x86_64
    image: postgres:17.0
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "a12345"
      POSTGRES_USER: "test-user"
      POSTGRES_DB: "test-db"
    networks:
      - simpler-tha

networks:
  simpler-tha:
