version: "3.3"

services:
  server:
    image: simpler-server
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - simpler-net

  postgres:
    platform: linux/x86_64
    image: postgres:17.0
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "a12345"
      POSTGRES_USER: "test-user"
      POSTGRES_DB: "test-db"
    networks:
      - simpler-net

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://test-user:a12345@postgres:5432/test-db?sslmode=disable", "up", "3" ]
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - simpler-net

networks:
  simpler-net: